name: Auto Update README

on:
  push:
    paths:
      - 'data/cards.json'
  schedule:
    - cron: '0 12 * * *'

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install urllib3
      - run: python scripts/generate_readme.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M')"
          git push
